package cff

import (
	"errors"
	"gopkg.in/yaml.v3"
)

//MarshalYAML is used to serialise a LicenseContainer
func (t LicenseContainer) MarshalYAML() (interface{}, error) {
	for _, license := range t.Data {
		if !ReferenceTypeExists(string(license)) {
			return nil, errors.New("invalid license: " + string(license))
		}
	}

	return t.Data, nil
}

//UnmarshalYAML creates a LicenseContainer from a license string or array
func (t *LicenseContainer) UnmarshalYAML(v *yaml.Node) error {
	if v.Kind == yaml.ScalarNode && LicenseExists(v.Value) {
		t.Data = []License{
			License(v.Value),
		}
	} else {
		var licenseArray []License
		err := v.Decode(&licenseArray)
		if err != nil {
			return err
		}
		for _, license := range licenseArray {
			if !LicenseExists(string(license)) {
				return errors.New("License " + string(license) + " does not exist")
			}
		}
		t.Data = licenseArray
	}

	return nil
}

//MakeLicenses creates a License array from a Licenses
func MakeLicenses(license ...License) LicenseContainer {
	return LicenseContainer{Data: license}
}

//MakeLicensesByString creates a License array from strings
func MakeLicensesByString(license ...string) LicenseContainer {
	var licenses = make([]License, len(license))
	for i, v := range license {
		licenses[i] = License(v)
	}
	return LicenseContainer{Data: licenses}
}

//LicenseExists checks if a License exists
func LicenseExists(license string) bool {
	switch License(license) {

	case LICENSE_0BSD:
		return true
	case LICENSE_AAL:
		return true
	case LICENSE_Abstyles:
		return true
	case LICENSE_Adobe2006:
		return true
	case LICENSE_AdobeGlyph:
		return true
	case LICENSE_ADSL:
		return true
	case LICENSE_AFL11:
		return true
	case LICENSE_AFL12:
		return true
	case LICENSE_AFL20:
		return true
	case LICENSE_AFL21:
		return true
	case LICENSE_AFL30:
		return true
	case LICENSE_Afmparse:
		return true
	case LICENSE_AGPL10:
		return true
	case LICENSE_AGPL10only:
		return true
	case LICENSE_AGPL10orlater:
		return true
	case LICENSE_AGPL30:
		return true
	case LICENSE_AGPL30only:
		return true
	case LICENSE_AGPL30orlater:
		return true
	case LICENSE_Aladdin:
		return true
	case LICENSE_AMDPLPA:
		return true
	case LICENSE_AML:
		return true
	case LICENSE_AMPAS:
		return true
	case LICENSE_ANTLRPD:
		return true
	case LICENSE_ANTLRPDfallback:
		return true
	case LICENSE_Apache10:
		return true
	case LICENSE_Apache11:
		return true
	case LICENSE_Apache20:
		return true
	case LICENSE_APAFML:
		return true
	case LICENSE_APL10:
		return true
	case LICENSE_APSL10:
		return true
	case LICENSE_APSL11:
		return true
	case LICENSE_APSL12:
		return true
	case LICENSE_APSL20:
		return true
	case LICENSE_Artistic10:
		return true
	case LICENSE_Artistic10cl8:
		return true
	case LICENSE_Artistic10Perl:
		return true
	case LICENSE_Artistic20:
		return true
	case LICENSE_Bahyph:
		return true
	case LICENSE_Barr:
		return true
	case LICENSE_Beerware:
		return true
	case LICENSE_BitTorrent10:
		return true
	case LICENSE_BitTorrent11:
		return true
	case LICENSE_blessing:
		return true
	case LICENSE_BlueOak100:
		return true
	case LICENSE_Borceux:
		return true
	case LICENSE_BSD1Clause:
		return true
	case LICENSE_BSD2Clause:
		return true
	case LICENSE_BSD2ClauseFreeBSD:
		return true
	case LICENSE_BSD2ClauseNetBSD:
		return true
	case LICENSE_BSD2ClausePatent:
		return true
	case LICENSE_BSD2ClauseViews:
		return true
	case LICENSE_BSD3Clause:
		return true
	case LICENSE_BSD3ClauseAttribution:
		return true
	case LICENSE_BSD3ClauseClear:
		return true
	case LICENSE_BSD3ClauseLBNL:
		return true
	case LICENSE_BSD3ClauseModification:
		return true
	case LICENSE_BSD3ClauseNoNuclearLicense:
		return true
	case LICENSE_BSD3ClauseNoNuclearLicense2014:
		return true
	case LICENSE_BSD3ClauseNoNuclearWarranty:
		return true
	case LICENSE_BSD3ClauseOpenMPI:
		return true
	case LICENSE_BSD4Clause:
		return true
	case LICENSE_BSD4ClauseShortened:
		return true
	case LICENSE_BSD4ClauseUC:
		return true
	case LICENSE_BSDProtection:
		return true
	case LICENSE_BSDSourceCode:
		return true
	case LICENSE_BSL10:
		return true
	case LICENSE_BUSL11:
		return true
	case LICENSE_bzip2105:
		return true
	case LICENSE_bzip2106:
		return true
	case LICENSE_CUDA10:
		return true
	case LICENSE_CAL10:
		return true
	case LICENSE_CAL10CombinedWorkException:
		return true
	case LICENSE_Caldera:
		return true
	case LICENSE_CATOSL11:
		return true
	case LICENSE_CCBY10:
		return true
	case LICENSE_CCBY20:
		return true
	case LICENSE_CCBY25:
		return true
	case LICENSE_CCBY30:
		return true
	case LICENSE_CCBY30AT:
		return true
	case LICENSE_CCBY30US:
		return true
	case LICENSE_CCBY40:
		return true
	case LICENSE_CCBYNC10:
		return true
	case LICENSE_CCBYNC20:
		return true
	case LICENSE_CCBYNC25:
		return true
	case LICENSE_CCBYNC30:
		return true
	case LICENSE_CCBYNC40:
		return true
	case LICENSE_CCBYNCND10:
		return true
	case LICENSE_CCBYNCND20:
		return true
	case LICENSE_CCBYNCND25:
		return true
	case LICENSE_CCBYNCND30:
		return true
	case LICENSE_CCBYNCND30IGO:
		return true
	case LICENSE_CCBYNCND40:
		return true
	case LICENSE_CCBYNCSA10:
		return true
	case LICENSE_CCBYNCSA20:
		return true
	case LICENSE_CCBYNCSA25:
		return true
	case LICENSE_CCBYNCSA30:
		return true
	case LICENSE_CCBYNCSA40:
		return true
	case LICENSE_CCBYND10:
		return true
	case LICENSE_CCBYND20:
		return true
	case LICENSE_CCBYND25:
		return true
	case LICENSE_CCBYND30:
		return true
	case LICENSE_CCBYND40:
		return true
	case LICENSE_CCBYSA10:
		return true
	case LICENSE_CCBYSA20:
		return true
	case LICENSE_CCBYSA20UK:
		return true
	case LICENSE_CCBYSA21JP:
		return true
	case LICENSE_CCBYSA25:
		return true
	case LICENSE_CCBYSA30:
		return true
	case LICENSE_CCBYSA30AT:
		return true
	case LICENSE_CCBYSA40:
		return true
	case LICENSE_CCPDDC:
		return true
	case LICENSE_CC010:
		return true
	case LICENSE_CDDL10:
		return true
	case LICENSE_CDDL11:
		return true
	case LICENSE_CDL10:
		return true
	case LICENSE_CDLAPermissive10:
		return true
	case LICENSE_CDLASharing10:
		return true
	case LICENSE_CECILL10:
		return true
	case LICENSE_CECILL11:
		return true
	case LICENSE_CECILL20:
		return true
	case LICENSE_CECILL21:
		return true
	case LICENSE_CECILLB:
		return true
	case LICENSE_CECILLC:
		return true
	case LICENSE_CERNOHL11:
		return true
	case LICENSE_CERNOHL12:
		return true
	case LICENSE_CERNOHLP20:
		return true
	case LICENSE_CERNOHLS20:
		return true
	case LICENSE_CERNOHLW20:
		return true
	case LICENSE_ClArtistic:
		return true
	case LICENSE_CNRIJython:
		return true
	case LICENSE_CNRIPython:
		return true
	case LICENSE_CNRIPythonGPLCompatible:
		return true
	case LICENSE_Condor11:
		return true
	case LICENSE_copyleftnext030:
		return true
	case LICENSE_copyleftnext031:
		return true
	case LICENSE_CPAL10:
		return true
	case LICENSE_CPL10:
		return true
	case LICENSE_CPOL102:
		return true
	case LICENSE_Crossword:
		return true
	case LICENSE_CrystalStacker:
		return true
	case LICENSE_CUAOPL10:
		return true
	case LICENSE_Cube:
		return true
	case LICENSE_curl:
		return true
	case LICENSE_DFSL10:
		return true
	case LICENSE_diffmark:
		return true
	case LICENSE_DOC:
		return true
	case LICENSE_Dotseqn:
		return true
	case LICENSE_DRL10:
		return true
	case LICENSE_DSDP:
		return true
	case LICENSE_dvipdfm:
		return true
	case LICENSE_ECL10:
		return true
	case LICENSE_ECL20:
		return true
	case LICENSE_eCos20:
		return true
	case LICENSE_EFL10:
		return true
	case LICENSE_EFL20:
		return true
	case LICENSE_DLDEBY20:
		return true
	case LICENSE_eGenix:
		return true
	case LICENSE_FDKAAC:
		return true
	case LICENSE_Elastic20:
		return true
	case LICENSE_Entessa:
		return true
	case LICENSE_EPICS:
		return true
	case LICENSE_EPL10:
		return true
	case LICENSE_EPL20:
		return true
	case LICENSE_ErlPL11:
		return true
	case LICENSE_etalab20:
		return true
	case LICENSE_EUDatagrid:
		return true
	case LICENSE_EUPL10:
		return true
	case LICENSE_EUPL11:
		return true
	case LICENSE_EUPL12:
		return true
	case LICENSE_Eurosym:
		return true
	case LICENSE_Fair:
		return true
	case LICENSE_Frameworx10:
		return true
	case LICENSE_FreeBSDDOC:
		return true
	case LICENSE_FreeImage:
		return true
	case LICENSE_FSFAP:
		return true
	case LICENSE_FSFUL:
		return true
	case LICENSE_FSFULLR:
		return true
	case LICENSE_FTL:
		return true
	case LICENSE_GD:
		return true
	case LICENSE_GFDL11:
		return true
	case LICENSE_GFDL11invariantsonly:
		return true
	case LICENSE_GFDL11invariantsorlater:
		return true
	case LICENSE_GFDL11noinvariantsonly:
		return true
	case LICENSE_GFDL11noinvariantsorlater:
		return true
	case LICENSE_GFDL11only:
		return true
	case LICENSE_GFDL11orlater:
		return true
	case LICENSE_GFDL12:
		return true
	case LICENSE_GFDL12invariantsonly:
		return true
	case LICENSE_GFDL12invariantsorlater:
		return true
	case LICENSE_GFDL12noinvariantsonly:
		return true
	case LICENSE_GFDL12noinvariantsorlater:
		return true
	case LICENSE_GFDL12only:
		return true
	case LICENSE_GFDL12orlater:
		return true
	case LICENSE_GFDL13:
		return true
	case LICENSE_GFDL13invariantsonly:
		return true
	case LICENSE_GFDL13invariantsorlater:
		return true
	case LICENSE_GFDL13noinvariantsonly:
		return true
	case LICENSE_GFDL13noinvariantsorlater:
		return true
	case LICENSE_GFDL13only:
		return true
	case LICENSE_GFDL13orlater:
		return true
	case LICENSE_Giftware:
		return true
	case LICENSE_GL2PS:
		return true
	case LICENSE_Glide:
		return true
	case LICENSE_Glulxe:
		return true
	case LICENSE_GLWTPL:
		return true
	case LICENSE_gnuplot:
		return true
	case LICENSE_GPL10:
		return true
	case LICENSE_GPL10only:
		return true
	case LICENSE_GPL10orlater:
		return true
	case LICENSE_GPL10PLUS:
		return true
	case LICENSE_GPL20:
		return true
	case LICENSE_GPL20only:
		return true
	case LICENSE_GPL20orlater:
		return true
	case LICENSE_GPL20withautoconfexception:
		return true
	case LICENSE_GPL20withbisonexception:
		return true
	case LICENSE_GPL20withclasspathexception:
		return true
	case LICENSE_GPL20withfontexception:
		return true
	case LICENSE_GPL20withGCCexception:
		return true
	case LICENSE_GPL20PLUS:
		return true
	case LICENSE_GPL30:
		return true
	case LICENSE_GPL30only:
		return true
	case LICENSE_GPL30orlater:
		return true
	case LICENSE_GPL30withautoconfexception:
		return true
	case LICENSE_GPL30withGCCexception:
		return true
	case LICENSE_GPL30PLUS:
		return true
	case LICENSE_gSOAP13b:
		return true
	case LICENSE_HaskellReport:
		return true
	case LICENSE_Hippocratic21:
		return true
	case LICENSE_HPND:
		return true
	case LICENSE_HPNDsellvariant:
		return true
	case LICENSE_HTMLTIDY:
		return true
	case LICENSE_IBMpibs:
		return true
	case LICENSE_ICU:
		return true
	case LICENSE_IJG:
		return true
	case LICENSE_ImageMagick:
		return true
	case LICENSE_iMatix:
		return true
	case LICENSE_Imlib2:
		return true
	case LICENSE_InfoZIP:
		return true
	case LICENSE_Intel:
		return true
	case LICENSE_IntelACPI:
		return true
	case LICENSE_Interbase10:
		return true
	case LICENSE_IPA:
		return true
	case LICENSE_IPL10:
		return true
	case LICENSE_ISC:
		return true
	case LICENSE_Jam:
		return true
	case LICENSE_JasPer20:
		return true
	case LICENSE_JPNIC:
		return true
	case LICENSE_JSON:
		return true
	case LICENSE_LAL12:
		return true
	case LICENSE_LAL13:
		return true
	case LICENSE_Latex2e:
		return true
	case LICENSE_Leptonica:
		return true
	case LICENSE_LGPL20:
		return true
	case LICENSE_LGPL20only:
		return true
	case LICENSE_LGPL20PLUS:
		return true
	case LICENSE_LGPL20orlater:
		return true
	case LICENSE_LGPL21PLUS:
		return true
	case LICENSE_LGPL30PLUS:
		return true
	case LICENSE_LGPL21:
		return true
	case LICENSE_LGPL21only:
		return true
	case LICENSE_LGPL21orlater:
		return true
	case LICENSE_LGPL30:
		return true
	case LICENSE_LGPL30only:
		return true
	case LICENSE_LGPL30orlater:
		return true
	case LICENSE_LGPLLR:
		return true
	case LICENSE_Linuxmanpagescopyleft:
		return true
	case LICENSE_Libpng:
		return true
	case LICENSE_libpng20:
		return true
	case LICENSE_libselinux10:
		return true
	case LICENSE_libtiff:
		return true
	case LICENSE_LiLiQP11:
		return true
	case LICENSE_LiLiQR11:
		return true
	case LICENSE_LiLiQRplus11:
		return true
	case LICENSE_LinuxOpenIB:
		return true
	case LICENSE_LPL10:
		return true
	case LICENSE_LPL102:
		return true
	case LICENSE_LPPL10:
		return true
	case LICENSE_LPPL11:
		return true
	case LICENSE_LPPL12:
		return true
	case LICENSE_LPPL13a:
		return true
	case LICENSE_LPPL13c:
		return true
	case LICENSE_MakeIndex:
		return true
	case LICENSE_MirOS:
		return true
	case LICENSE_MIT:
		return true
	case LICENSE_MIT0:
		return true
	case LICENSE_MITadvertising:
		return true
	case LICENSE_MITCMU:
		return true
	case LICENSE_MITenna:
		return true
	case LICENSE_MITfeh:
		return true
	case LICENSE_MITModernVariant:
		return true
	case LICENSE_MITopengroup:
		return true
	case LICENSE_MITNFA:
		return true
	case LICENSE_Motosoto:
		return true
	case LICENSE_mpich2:
		return true
	case LICENSE_MPL10:
		return true
	case LICENSE_MPL11:
		return true
	case LICENSE_MPL20:
		return true
	case LICENSE_MPL20nocopyleftexception:
		return true
	case LICENSE_MSPL:
		return true
	case LICENSE_MSRL:
		return true
	case LICENSE_MTLL:
		return true
	case LICENSE_MulanPSL10:
		return true
	case LICENSE_MulanPSL20:
		return true
	case LICENSE_Multics:
		return true
	case LICENSE_Mup:
		return true
	case LICENSE_NAIST2003:
		return true
	case LICENSE_NASA13:
		return true
	case LICENSE_Naumen:
		return true
	case LICENSE_NBPL10:
		return true
	case LICENSE_NCGLUK20:
		return true
	case LICENSE_NCSA:
		return true
	case LICENSE_NetSNMP:
		return true
	case LICENSE_NetCDF:
		return true
	case LICENSE_Newsletr:
		return true
	case LICENSE_NGPL:
		return true
	case LICENSE_NISTPD:
		return true
	case LICENSE_NISTPDfallback:
		return true
	case LICENSE_NLOD10:
		return true
	case LICENSE_NLOD20:
		return true
	case LICENSE_NLPL:
		return true
	case LICENSE_Nokia:
		return true
	case LICENSE_NOSL:
		return true
	case LICENSE_Noweb:
		return true
	case LICENSE_NPL10:
		return true
	case LICENSE_NPL11:
		return true
	case LICENSE_NPOSL30:
		return true
	case LICENSE_NRL:
		return true
	case LICENSE_NTP:
		return true
	case LICENSE_NTP0:
		return true
	case LICENSE_Nunit:
		return true
	case LICENSE_OUDA10:
		return true
	case LICENSE_OCCTPL:
		return true
	case LICENSE_OCLC20:
		return true
	case LICENSE_ODbL10:
		return true
	case LICENSE_ODCBy10:
		return true
	case LICENSE_OFL10:
		return true
	case LICENSE_OFL10noRFN:
		return true
	case LICENSE_OFL10RFN:
		return true
	case LICENSE_OFL11:
		return true
	case LICENSE_OFL11noRFN:
		return true
	case LICENSE_OFL11RFN:
		return true
	case LICENSE_OGC10:
		return true
	case LICENSE_OGDLTaiwan10:
		return true
	case LICENSE_OGLCanada20:
		return true
	case LICENSE_OGLUK10:
		return true
	case LICENSE_OGLUK20:
		return true
	case LICENSE_OGLUK30:
		return true
	case LICENSE_OGTSL:
		return true
	case LICENSE_OLDAP11:
		return true
	case LICENSE_OLDAP12:
		return true
	case LICENSE_OLDAP13:
		return true
	case LICENSE_OLDAP14:
		return true
	case LICENSE_OLDAP20:
		return true
	case LICENSE_OLDAP201:
		return true
	case LICENSE_OLDAP21:
		return true
	case LICENSE_OLDAP22:
		return true
	case LICENSE_OLDAP221:
		return true
	case LICENSE_OLDAP222:
		return true
	case LICENSE_OLDAP23:
		return true
	case LICENSE_OLDAP24:
		return true
	case LICENSE_OLDAP25:
		return true
	case LICENSE_OLDAP26:
		return true
	case LICENSE_OLDAP27:
		return true
	case LICENSE_OLDAP28:
		return true
	case LICENSE_OML:
		return true
	case LICENSE_OpenSSL:
		return true
	case LICENSE_OPL10:
		return true
	case LICENSE_OSETPL21:
		return true
	case LICENSE_OSL10:
		return true
	case LICENSE_OSL11:
		return true
	case LICENSE_OSL20:
		return true
	case LICENSE_OSL21:
		return true
	case LICENSE_OSL30:
		return true
	case LICENSE_Parity600:
		return true
	case LICENSE_Parity700:
		return true
	case LICENSE_PDDL10:
		return true
	case LICENSE_PHP30:
		return true
	case LICENSE_PHP301:
		return true
	case LICENSE_Plexus:
		return true
	case LICENSE_PolyFormNoncommercial100:
		return true
	case LICENSE_PolyFormSmallBusiness100:
		return true
	case LICENSE_PostgreSQL:
		return true
	case LICENSE_PSF20:
		return true
	case LICENSE_psfrag:
		return true
	case LICENSE_psutils:
		return true
	case LICENSE_Python20:
		return true
	case LICENSE_Qhull:
		return true
	case LICENSE_QPL10:
		return true
	case LICENSE_Rdisc:
		return true
	case LICENSE_RHeCos11:
		return true
	case LICENSE_RPL11:
		return true
	case LICENSE_RPL15:
		return true
	case LICENSE_RPSL10:
		return true
	case LICENSE_RSAMD:
		return true
	case LICENSE_RSCPL:
		return true
	case LICENSE_Ruby:
		return true
	case LICENSE_SAXPD:
		return true
	case LICENSE_Saxpath:
		return true
	case LICENSE_SCEA:
		return true
	case LICENSE_Sendmail:
		return true
	case LICENSE_Sendmail823:
		return true
	case LICENSE_SGIB10:
		return true
	case LICENSE_SGIB11:
		return true
	case LICENSE_SGIB20:
		return true
	case LICENSE_SHL05:
		return true
	case LICENSE_SHL051:
		return true
	case LICENSE_SimPL20:
		return true
	case LICENSE_SISSL:
		return true
	case LICENSE_SISSL12:
		return true
	case LICENSE_Sleepycat:
		return true
	case LICENSE_SMLNJ:
		return true
	case LICENSE_SMPPL:
		return true
	case LICENSE_SNIA:
		return true
	case LICENSE_Spencer86:
		return true
	case LICENSE_Spencer94:
		return true
	case LICENSE_Spencer99:
		return true
	case LICENSE_SPL10:
		return true
	case LICENSE_SSHOpenSSH:
		return true
	case LICENSE_SSHshort:
		return true
	case LICENSE_SSPL10:
		return true
	case LICENSE_StandardMLNJ:
		return true
	case LICENSE_SchemeReport:
		return true
	case LICENSE_SugarCRM113:
		return true
	case LICENSE_SWL:
		return true
	case LICENSE_TAPROHL10:
		return true
	case LICENSE_TCL:
		return true
	case LICENSE_TCPwrappers:
		return true
	case LICENSE_TMate:
		return true
	case LICENSE_TORQUE11:
		return true
	case LICENSE_TOSL:
		return true
	case LICENSE_TUBerlin10:
		return true
	case LICENSE_TUBerlin20:
		return true
	case LICENSE_UCL10:
		return true
	case LICENSE_UnicodeDFS2015:
		return true
	case LICENSE_UnicodeDFS2016:
		return true
	case LICENSE_UnicodeTOU:
		return true
	case LICENSE_Unlicense:
		return true
	case LICENSE_UPL10:
		return true
	case LICENSE_Vim:
		return true
	case LICENSE_VOSTROM:
		return true
	case LICENSE_VSL10:
		return true
	case LICENSE_W3C:
		return true
	case LICENSE_W3C19980720:
		return true
	case LICENSE_W3C20150513:
		return true
	case LICENSE_Watcom10:
		return true
	case LICENSE_Wsuipa:
		return true
	case LICENSE_WTFPL:
		return true
	case LICENSE_wxWindows:
		return true
	case LICENSE_X11distributemodificationsvariant:
		return true
	case LICENSE_X11:
		return true
	case LICENSE_Xerox:
		return true
	case LICENSE_XFree8611:
		return true
	case LICENSE_xinetd:
		return true
	case LICENSE_Xnet:
		return true
	case LICENSE_xpp:
		return true
	case LICENSE_XSkat:
		return true
	case LICENSE_YPL10:
		return true
	case LICENSE_YPL11:
		return true
	case LICENSE_Zed:
		return true
	case LICENSE_Zend20:
		return true
	case LICENSE_Zimbra13:
		return true
	case LICENSE_Zimbra14:
		return true
	case LICENSE_Zlib:
		return true
	case LICENSE_zlibacknowledgement:
		return true
	case LICENSE_ZPL11:
		return true
	case LICENSE_ZPL20:
		return true
	case LICENSE_ZPL21:
		return true
	case LICENSE_Apps2p:
		return true
	case LICENSE_BSD3ClauseNoMilitaryLicense:
		return true
	case LICENSE_CCBY25AU:
		return true
	case LICENSE_CCBY30DE:
		return true
	case LICENSE_CCBY30NL:
		return true
	case LICENSE_CCBYNC30DE:
		return true
	case LICENSE_CCBYNCND30DE:
		return true
	case LICENSE_CCBYNCSA20FR:
		return true
	case LICENSE_CCBYNCSA20UK:
		return true
	case LICENSE_CCBYNCSA30DE:
		return true
	case LICENSE_CCBYNCSA30IGO:
		return true
	case LICENSE_CCBYND30DE:
		return true
	case LICENSE_CCBYSA30DE:
		return true
	case LICENSE_CDLAPermissive20:
		return true
	case LICENSE_COIL10:
		return true
	case LICENSE_CommunitySpec10:
		return true
	case LICENSE_OPUBL10:
		return true
	default:
		return false
	}
}
